apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: smanismaniquorum
  namespace: smani-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: smanismaniquorum
  helmVersion: v3
  chart:
    git: https://github.com/manikanta-darsi/bevel.git
    ref: dev-ansible
    path: platforms/quorum/charts/node_quorum_member
  values:
    replicaCount: 1
    metadata:
      namespace: smani-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: smani
      status: default
      consensus: raft
      subject: O=Store,OU=Store,L=40.73/-74/New York,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/smani-quo/crypto/smani
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumsmani
    tessera:
      dburl: "jdbc:mysql://smani-tessera:3306/demodb"
      dbusername: demouser
      url: "https://smani.rc.dev2.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "http://smani-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://cmani.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://mmani.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://smani.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://wmani.rc.dev2.aws.blockchaincloudpoc-develop.com
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImFsbG9jIjogewogICAgICAgICIxNjQ3YjMyNmE1YzE5YzM5M2EzOWJkNTMwYzg3NDljMGM2MTVmYjFhIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjQ2NDc2ODJjZjlkYWUwNzRhMWQ2NGY1ZjI1ZTU3ODQ5N2VjNTM0NTUiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfSwKICAgICAgICAiNWZlMTc1NGE2NjY0OWI3NzFkYTE2Yzg0ZGVlMjc3ZTE4MTQ1ZDY4ZCI6IHsKICAgICAgICAgICAgImJhbGFuY2UiOiAiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgICAgICB9LAogICAgICAgICJlZGM3ZjlmNWY5YmZlN2UwMzY1YTU1MGJlM2NkZmE2Y2FjYTdiNWJmIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0KICAgIH0sCiAgICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICJjb25maWciOiB7CiAgICAgICAgImJ5emFudGl1bUJsb2NrIjogMCwKICAgICAgICAiY2hhaW5JZCI6IDEwLAogICAgICAgICJjb25zdGFudGlub3BsZUJsb2NrIjogMCwKICAgICAgICAiZWlwMTUwQmxvY2siOiAwLAogICAgICAgICJlaXAxNTBIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAgICAgImVpcDE1NUJsb2NrIjogMCwKICAgICAgICAiZWlwMTU4QmxvY2siOiAwLAogICAgICAgICJob21lc3RlYWRCbG9jayI6IDAsCiAgICAgICAgImlzUXVvcnVtIjogdHJ1ZSwKICAgICAgICAicGV0ZXJzYnVyZ0Jsb2NrIjogMCwKICAgICAgICAicmFmdFNlY29uZHMiOiB0cnVlLAogICAgICAgICJ0eG5TaXplTGltaXQiOiAxMjgKICAgIH0sCiAgICAiZGlmZmljdWx0eSI6ICIweDAiLAogICAgImV4dHJhRGF0YSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImdhc0xpbWl0IjogIjB4RTAwMDAwMDAwMCIsCiAgICAibWl4aGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjQ3NTcyNjE2YzY1Nzg3MzY1NjQ2YzY1NzgiLAogICAgIm5vbmNlIjogIjB4MCIsCiAgICAicGFyZW50SGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgInRpbWVzdGFtcCI6ICIweDAwIgp9
    staticnodes: 
      [
    "enode://f1c72e1a79047e4cd8de8b4b4a2c944aa5fd0780c3c8b49452d94e3897a4cfae998fb288a776fbb904b6ab3f226fc802f246e12421cce614dd8be8832fac5fea@cmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15010?discport=0&raftport=15012",
    "enode://c7c11a44810baa20aa6c5b2e8af0a25626c713e54302970582b3db1ecd03e263f4e00125aa36296f1ffecca8b030ecbe25c937f7746b7610d11a5c494e939c28@mmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15013?discport=0&raftport=15015",
    "enode://da9db05aa50df161b93d9fafa7169bb266f13f443f04bd1cda76df8a02d32e88e4c1bcbdcce53656825909be92b98f588869fff91fcd870304e6bda81e8fc393@smani.rc.dev2.aws.blockchaincloudpoc-develop.com:15016?discport=0&raftport=15018",
    "enode://4dcb8c7f55be14bffb47d8fe9b56358d0397a577ef3f2afbe172308e61477e1b7bb906c371585f71bd75598dc55ad939332587f1a7e3b94e01092924b28c29ff@wmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15019?discport=0&raftport=15031"
]
    proxy:
      provider: "ambassador"
      external_url: smani.rc.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443
      rpcport: 15017
      quorumport: 15016
  
      portRaft: 15018
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
