apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: smanismanitessera
  namespace: smani-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: smanismanitessera
  helmVersion: v3
  chart:
    git: https://github.com/manikanta-darsi/bevel.git
    ref: dev-ansible
    path: platforms/quorum/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: smani-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      pullPolicy: IfNotPresent
    node:
      name: smani
      status: default
      consensus: raft
      subject: O=Store,OU=Store,L=40.73/-74/New York,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretengine: secretsv2
      tmsecretpath: smani-quo/crypto/smani/tm      
      secretprefix: secretsv2/data/smani-quo/crypto/smani
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumsmani
    tessera:
      dburl: "jdbc:mysql://smani-tessera:3306/demodb"
      dbusername: demouser
      url: "https://smani.rc.dev2.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "http://smani-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://cmani.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://mmani.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://smani.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://wmani.rc.dev2.aws.blockchaincloudpoc-develop.com
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImFsbG9jIjogewogICAgICAgICI4YmYxNTVlZWU5MTllMGY1NjQ2ZTA1MzI5OWUxZWFkMjE0ZDNiMzQyIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjk5Njg5NTU3Y2FlNzFhMjE3NjNmMzFkNWMyNWMwZDdiYjNkYzYxN2MiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfSwKICAgICAgICAiZDY0NWM3ZWNjMmMwNjZmZDJmNTFmYTVhNzZjOTI5ZjM0MDhkOGM1YiI6IHsKICAgICAgICAgICAgImJhbGFuY2UiOiAiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgICAgICB9LAogICAgICAgICJkZjg5MjE1YjE3ZmUwYjFkOGM1NmFlNGJmNDE5ODg4MjE2ZmYyMGJjIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0KICAgIH0sCiAgICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICJjb25maWciOiB7CiAgICAgICAgImJ5emFudGl1bUJsb2NrIjogMCwKICAgICAgICAiY2hhaW5JZCI6IDEwLAogICAgICAgICJjb25zdGFudGlub3BsZUJsb2NrIjogMCwKICAgICAgICAiZWlwMTUwQmxvY2siOiAwLAogICAgICAgICJlaXAxNTBIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAgICAgImVpcDE1NUJsb2NrIjogMCwKICAgICAgICAiZWlwMTU4QmxvY2siOiAwLAogICAgICAgICJob21lc3RlYWRCbG9jayI6IDAsCiAgICAgICAgImlzUXVvcnVtIjogdHJ1ZSwKICAgICAgICAicGV0ZXJzYnVyZ0Jsb2NrIjogMCwKICAgICAgICAicmFmdFNlY29uZHMiOiB0cnVlLAogICAgICAgICJ0eG5TaXplTGltaXQiOiAxMjgKICAgIH0sCiAgICAiZGlmZmljdWx0eSI6ICIweDAiLAogICAgImV4dHJhRGF0YSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImdhc0xpbWl0IjogIjB4RTAwMDAwMDAwMCIsCiAgICAibWl4aGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjQ3NTcyNjE2YzY1Nzg3MzY1NjQ2YzY1NzgiLAogICAgIm5vbmNlIjogIjB4MCIsCiAgICAicGFyZW50SGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgInRpbWVzdGFtcCI6ICIweDAwIgp9
    staticnodes: 
      [
    "enode://cf8fe37881e4dec8608e3964578ce97961dd8eb3a4f5a41b159ba95eb4af5c3467151010c6934b2ef662e30b188167bab7874819d35044f2d46d9b5daad6064e@cmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15010?discport=0&raftport=15012",
    "enode://c6e5072236d6f1aafb368555454495054fceb361f6dc8f9c5e9daf4dd476c1e33aebf12965e893e6c9dcfa9fac8604ff3c9710c0ab54b187007ea72011579de0@mmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15013?discport=0&raftport=15015",
    "enode://f1d78e84a7f42c8f56b1cbf6b87b9c2d78e3608dfb9298e50b98f06fd34edee55a4e5a290a7677cecf4c6e33e95876ea42c0ccf936e2b7b6647e10bbee82ac23@smani.rc.dev2.aws.blockchaincloudpoc-develop.com:15016?discport=0&raftport=15018",
    "enode://388e5eec9dfc266562a44de92abb4f612b46694a162c0e42f31067f46bcab63de5fe08f7f7989a504dd6d2df3bc9bc3aa7ee9d3c68b024db84018c96b5abd2fe@wmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15019?discport=0&raftport=15031"
]
    proxy:
      provider: "ambassador"
      external_url: smani.rc.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443
      rpcport: 15017
      quorumport: 15016
      clientport: 8888
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
