##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
- name: Verify
  hosts: localhost
  tasks:
  # - debug:
  #      var: node_name
  - name: Check if the {{ node.name | lower }}-generate-ambassador-certs-job value file has been created
    stat:
      path: "{{ playbook_dir }}/build/platforms/quorum/releases/dev/store/{{ node.name | lower }}-generate-ambassador-certs-job.yaml"
    register: generate-ambassador-certs-job_file_check

  - name: Assert if the value file has been created
    assert:
      that: generate-ambassador-certs-job.stat.exists
