apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wmani-tessera-job
  namespace: wmani-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: wmani-tessera-job
  chart:
    path: platforms/quorum/charts/tessera_key_mgmt
    git: https://github.com/manikanta-darsi/bevel.git
    ref: dev-ansible
  values:
    peer:
      name: wmani  
    metadata:
      name: wmani-tessera-job
      namespace: wmani-quo    
    image:      
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretengine: secretsv2      
      authpath: quorumwmani
      keyprefix: wmani-quo/crypto
      role: vault-role
      serviceaccountname: vault-auth
      tmprefix: secretsv2/data/wmani-quo/crypto
