############################################################################################
# This task deploys the external chaincode server
- name: Deploy the external chaincode server
  include_tasks: nested_main.yaml
  vars:
    chaincode_name: "{{ peer.chaincode.name | lower }}"
    chaincode_version: "{{ peer.chaincode.version }}"
    org: "{{ item }}"
  loop: "{{ peers[0:1] }}"
  loop_control:
    loop_var: peer
    extended: true
  when:
    - peer.chaincode is defined
    - peer.chaincode.external_chaincode is defined
    - peer.chaincode.external_chaincode == true