# Check or Wait if commit-chaincode is already run for v.2.x

############################################################################################
# Check if external-chaincode-server is already running
- name: Check external-chaincode-server exists
  k8s_info:
    kind: Pod
    namespace: "{{ org_ns }}"
    name: "chaincode-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}-{{ org_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: ext_chaincode_server

############################################################################################
# checking for fabric cli
- name: "Check if fabric cli is already present"
  k8s_info:
    kind: Pod
    namespace: "{{ org.name }}-net"
    kubeconfig: "{{ org.k8s.config_file }}"
    context: "{{ org.k8s.context }}"
    label_selectors:
      - app = cli
  register: existing_cli

- debug:
    var: existing_cli

# Create the value file for org first peer
- name: Create CLI pod for each peer when enabled and it's not existed
  include_role:
    name: "create/cli_pod"
  vars:
    peers: "{{ org.services.peers[0:1] }}"
    docker_url: "{{ network.docker.url }}"
  when:
    - org.type == "peer"
    - existing_cli.resources|length == 0

# waiting for fabric cli
- name: "Check if fabric cli is present"
  k8s_info:
    kind: Pod
    namespace: "{{ org.name }}-net"
    kubeconfig: "{{ org.k8s.config_file }}"
    context: "{{ org.k8s.context }}"
    label_selectors:
      - app = cli
  register: get_cli
  until: ("Running" in get_cli|json_query('resources[*].status.phase'))
  retries: "{{ network.env.retry_count}}"
  delay: 40

############################################################################################
# This task packages and installs external chaincode
- name: Fetch the ccid from the Peer CLI
  shell: |
    export PEER_CLI=$(KUBECONFIG={{ kubernetes.config_file }} kubectl get po -n {{ org_ns }} | grep "{{ peer.name }}-cli" | awk '{print $1}')
    KUBECONFIG={{ kubernetes.config_file }} kubectl exec -it -n {{ org_ns }} ${PEER_CLI} -- peer lifecycle chaincode queryinstalled | grep {{ chaincode_name }}_{{ chaincode_version }} | awk '{print $3}' | sed 's/, / /g'  > ./build/ccid.txt
  when: ext_chaincode_server.resources|length == 0

############################################################################################
# This task fetches the chaincode ID
- name: Fetch the ccid to var
  command: cat ./build/ccid.txt
  register: ccid
  when: ext_chaincode_server.resources|length == 0

############################################################################################
# Check if private credentials exist already
- name: "Checking if the docker credentials already exists"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/setup"
  vars:
    check: "chaincode_private_registry_credentials"
    component_name: "{{ item.name | lower }}-net"
  register: get_chaincode_private_regcred
  when: peer.chaincode.private_registry is defined and peer.chaincode.private_registry == true

# This task creates the docker pull credentials for private image registry
- name: Create the private registry pull credentials
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl create secret -n {{ component_name }} docker-registry chaincode-private-regcred --docker-server={{ peer.chaincode.registry.server }} --docker-username={{ peer.chaincode.registry.username }} --docker-password={{ peer.chaincode.registry.password }} --docker-email="test@abc.mail"
  vars:
    component_name: "{{ item.name | lower }}-net"
  when:
    - peer.chaincode.private_registry is defined and peer.chaincode.private_registry == true
    - get_chaincode_private_regcred.resources|length == 0

############################################################################################
# This task creates value files for chaincode server
- name: Create Value files for chaincode server
  include_role:
    name: helm_component
  vars:
    name: "{{ item.name | lower }}"
    type: "external_chaincode"
    component_name: "chaincode-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}-{{ org_name }}"
    chaincode_image: "{{ peer.chaincode.image }}"
    peer_name: "{{ peer.name }}"
    chaincode_ns: "{{ org_ns }}"
    provider: "{{ item.cloud_provider }}"
    alpine_image: "{{ docker_url }}/alpine-utils:1.0"
  when: ext_chaincode_server.resources|length == 0

############################################################################################
# Git Push : Pushes the above generated files to git directory
- name: Git Push
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ item.gitops.git_repo }}"
    GIT_USERNAME: "{{ item.gitops.username }}"
    GIT_EMAIL: "{{ item.gitops.email }}"
    GIT_PASSWORD: "{{ item.gitops.password }}"
    GIT_BRANCH: "{{ item.gitops.branch }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "[ci skip] Pushing chaincode server files"
  when: ext_chaincode_server.resources|length == 0

############################################################################################
# Wait for chaincode server pod to be in the state of running
- name: "Waiting for chaincode server pod chaincode-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}-{{ org_name }} in {{ item.name | lower }}-net"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ item.name | lower }}-net"
    component_name: "chaincode-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}-{{ org_name }}"
    kubernetes: "{{ item.k8s }}"
    label_selectors:
      - app = {{ component_name }}
  when: ext_chaincode_server.resources|length == 0
