apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-cmani
  namespace: cmani-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-cmani
  chart:
    git: https://github.com/manikanta-darsi/bevel.git
    ref: dev-chain
    path: platforms/hyperledger-fabric/charts/anchorpeer
    secretRef:
      name: gitcredentials
  values:
    metadata:
      namespace: cmani-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.cmani-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: cmaniMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: dev-manicmani-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/cmani-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/cmani-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer7.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      Ct0CChgKFggCGgYIw5/6lQYiCmFsbGNoYW5uZWwSwAIKvQIKCmFsbGNoYW5uZWwSYRJfCgtBcHBs
      aWNhdGlvbhJQCAESTAoIY21hbmlNU1ASQBoHCgNNU1ASACILCgdXcml0ZXJzEgAiCgoGQWRtaW5z
      EgAiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAaywESyAEKC0FwcGxpY2F0aW9uErgBCAES
      swEKCGNtYW5pTVNQEqYBCAEaWgoLQW5jaG9yUGVlcnMSSxJBCj8KOnBlZXIwLmNtYW5pLW5ldC5o
      Zi5kZXYyLmF3cy5ibG9ja2NoYWluY2xvdWRwb2MtZGV2ZWxvcC5jb20Q+0EaBkFkbWlucxoHCgNN
      U1ASACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5z
      EgAqBkFkbWlucw==

