apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cmani-peer0
  namespace: cmani-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cmani-peer0
  chart:
    git: https://github.com/manikanta-darsi/bevel.git
    ref: dev-chain
    path: platforms/hyperledger-fabric/charts/peernode    
    secretRef:
      name: gitcredentials
  values:
    metadata:
      namespace: cmani-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.cmani-net:7051
      gossipexternalendpoint: peer0.cmani-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: cmaniMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: cmani-user

    storage:
      peer:
        storageclassname: cmanisc
        storagesize: 512Mi
      couchdb:
        storageclassname: cmanisc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: dev-manicmani-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/cmani-net/peers/peer0.cmani-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/cmani-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/cmani-net/couchdb/cmani?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
