apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: smani-tessera-job
  namespace: smani-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: smani-tessera-job
  chart:
    path: platforms/quorum/charts/tessera_key_mgmt
    git: https://github.com/manikanta-darsi/bevel.git
    ref: dev-ansible
  values:
    peer:
      name: smani  
    metadata:
      name: smani-tessera-job
      namespace: smani-quo    
    image:      
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretengine: secretsv2      
      authpath: quorumsmani
      keyprefix: smani-quo/crypto
      role: vault-role
      serviceaccountname: vault-auth
      tmprefix: secretsv2/data/smani-quo/crypto
