apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cmani-net-ca-tools
  namespace: cmani-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cmani-net-ca-tools
  chart:
    git: https://github.com/manikanta-darsi/bevel.git
    ref: dev-chain
    path: platforms/hyperledger-fabric/charts/catools
    secretRef:
      name: gitcredentials
  values:
    metadata:
      namespace: cmani-net
      name: ca-tools
      component_type: peer
      org_name: cmani
      proxy: haproxy
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      
    storage:
      storageclassname: cmanisc
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: dev-manicmani-net-auth
      secretmsp: secretsv2/data/crypto/peerOrganizations/cmani-net/users/admin/msp
      secrettls: secretsv2/data/crypto/peerOrganizations/cmani-net/users/admin/tls
      secretorderer: secretsv2/data/crypto/peerOrganizations/cmani-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/cmani-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/cmani-net/orderer/tls
      secretambassador: secretsv2/data/crypto/peerOrganizations/cmani-net/ambassador
      secretcert: secretsv2/data/crypto/peerOrganizations/cmani-net/ca?ca.cmani-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/cmani-net/ca?cmani-net-CA.key
      secretcouchdb: secretsv2/data/credentials/cmani-net/couchdb/cmani
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/cmani-net/msp/config
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com
      component_subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      cert_subject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.cmani-net:7054

    orderers:
      name: orderer7-orderer8-orderer9-
    orderers_info:
      - name: orderer7
        path: "certs/orderer7-ca.crt"
      - name: orderer8
        path: "certs/orderer8-ca.crt"
      - name: orderer9
        path: "certs/orderer9-ca.crt"

    peers:
      name: peer0,-      
    peer_count: "1"
    checks:
      refresh_cert_value: False
      add_peer_value: False
