apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: doormanma
  annotations:
    fluxcd.io/automated: "false"
  namespace: smani-ns
spec:
  releaseName: doormanma
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda/charts/doorman-tls
      sourceRef:
        kind: GitRepository
        name: flux-dev-mani
        namespace: flux-dev-mani
  values:
    nodeName: doormanma
    metadata:
      namespace: smani-ns
    image:
      authusername: sa
      containerName: ghcr.io/hyperledger/bevel-doorman-linuxkit:latest
      env:
      - name: DOORMAN_PORT
        value: 8080
      - name: DOORMAN_ROOT_CA_NAME
        value: CN=Corda Doorman CA,OU=DLT,O=DLT,L=Berlin,C=DE
      - name: DOORMAN_TLS
        value: true
      - name: DOORMAN_DB
        value: /opt/doorman/db
      - name: DOORMAN_AUTH_USERNAME
        value: sa
      - name: DB_URL
        value: mongodb-doormanma
      - name: DB_PORT
        value: 27017
      - name: DATABASE
        value: admin
      - name: DB_USERNAME
        value: doormanma
      imagePullSecret: regcred
      tlsCertificate: true
      initContainerName: ghcr.io/hyperledger/alpine-utils:1.0
      mountPath:
        basePath: /opt/doorman
    storage:
      memory: 512Mi
      name: awsstorageclass
    mountPath:
      basePath: /opt/doorman
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordadoormanma
      serviceaccountname: vault-auth
      certsecretprefix: doormanma/data/certs
      dbcredsecretprefix: doormanma/data/credentials/mongodb
      secretdoormanpass: doormanma/data/credentials/userpassword
      tlscertsecretprefix: doormanma/data/tlscerts
      dbcertsecretprefix: doormanma/data/certs
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
      dburl: mongodb-doormanma:27017
    service:
      port: 8080
      targetPort: 8080
      type: ClusterIP
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    ambassador:
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
