apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmani-ambassador-job
  namespace: cmani-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: cmani-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/generate_ambassador_certs
    sourceRef:
      kind: GitRepository
      name: flux-dev-mani
      namespace: flux-dev-mani
  values:
    metadata:
      name: cmani-ambassador-job
      namespace: cmani-bes
    image:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: cmani
      clientport: 8888
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretengine: secretsv2
      authpath: besucmani
      rootcasecret: secretsv2/data/cmani-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: secretsv2/data/cmani-bes/crypto/cmani/tls
      role: vault-role
      serviceaccountname: vault-auth
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: cmani.bes.dev2.aws.blockchaincloudpoc-develop.com
      domain_name_priv: cmani.cmani-bes
      domain_name_tessera: cmani-tessera.cmani-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2
