apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmani-vaultk8s-job
  namespace: cmani-bes
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cmani-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/vault-k8s-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-dev-mani
      namespace: flux-dev-mani
  values:
    metadata:
      name: cmani-vaultk8s-job
      namespace: cmani-bes
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: besucmani
      policy: vault-crypto-organization-cmani-ro
      policydata: "{\n  \"policy\": \"path \\\"secretsv2/data/cmani-bes/crypto/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\", \\\"create\\\", \\\"update\\\"]\n  }\n  path \\\"secretsv2/data/cmani-bes/smartContracts/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\"]\n  }\"\n}"
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://C8FA1454BFC54EBEAC7D6A70501769F2.sk1.eu-west-1.eks.amazonaws.com
