apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mmani-frontend
  namespace: mmani-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/frontend
    git: "https://github.com/manikanta-darsi/bevel.git"
    ref: "flux"
  releaseName: mmaniquorum-frontend
  values:
    nodeName: mmani-frontend
    metadata:
      namespace: mmani-quo
    replicaCount: 1
    frontend:
      serviceType: ClusterIP
      nodePorts:
        port: 8080
        targetPort: 80
      image: ghcr.io/hyperledger/bevel-supplychain-frontend:stable
      pullPolicy: Always
      pullSecrets: regcred
      env:
        webserver: https://mmaniapi.rc.dev2.aws.blockchaincloudpoc-develop.com
    deployment:
      annotations: {}
    proxy:
      provider: ambassador
      peer_name: mmani
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      ambassador_secret: mmani-ambassador-certs
