apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mmanimmaniquorum
  namespace: mmani-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mmanimmaniquorum
  helmVersion: v3
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/node_quorum_member
    sourceRef:
      kind: GitRepository
      name: flux-dev-mani
      namespace: flux-dev-mani
  values:
    replicaCount: 1
    metadata:
      namespace: mmani-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: mmani
      status: default
      consensus: raft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/mmani-quo/crypto/mmani
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: tm
      role: vault-role
      authpath: quorummmani
    tessera:
      dburl: "jdbc:mysql://mmani-tessera:3306/demodb"
      dbusername: demouser
      url: "https://mmani.rc.dev2.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "http://mmani-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://cmani.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://mmani.rc.dev2.aws.blockchaincloudpoc-develop.com
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImFsbG9jIjogewogICAgICAgICIwY2UyMGQ0ZDE5OTNjNTBlZjI1ZjJhNjA2OGYwMWRlNzMyOGM5ZTBkIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjY3MGM4NTBlODczNDVjYTljZjM5Nzk4ZjM2OTBmNjVlOTI0YTNmYzIiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfQogICAgfSwKICAgICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImNvbmZpZyI6IHsKICAgICAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgICAgICJjaGFpbklkIjogMTAsCiAgICAgICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAgICAgImVpcDE1MEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICAgICAiZWlwMTU1QmxvY2siOiAwLAogICAgICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAgICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgICAgICJwZXRlcnNidXJnQmxvY2siOiAwLAogICAgICAgICJyYWZ0U2Vjb25kcyI6IHRydWUsCiAgICAgICAgInR4blNpemVMaW1pdCI6IDEyOAogICAgfSwKICAgICJkaWZmaWN1bHR5IjogIjB4MCIsCiAgICAiZXh0cmFEYXRhIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAiZ2FzTGltaXQiOiAiMHhFMDAwMDAwMDAwIiwKICAgICJtaXhoYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA2NDc1NzI2MTZjNjU3ODczNjU2NDZjNjU3OCIsCiAgICAibm9uY2UiOiAiMHgwIiwKICAgICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAidGltZXN0YW1wIjogIjB4MDAiCn0=
    staticnodes:
      [
    "enode://9bf031bbc38e7a40128078cd4ec2f3f659a70fde1a901ebeca1bbca72b368358d33fa21f2558050b862667848e7cc7112e843f027444ebeb76caa39de4758b99@cmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15010?discport=0&raftport=15012",
    "enode://54cf72e1c604802988648e8eee7c1b7a0aedffdd123b66cecbd41266fd9bf27cfdf4083be24cab0162829b7a9e06216e8a2333eb1ef6f049bb0a1ada1e6217a2@mmani.rc.dev2.aws.blockchaincloudpoc-develop.com:15013?discport=0&raftport=15015"
]
    proxy:
      provider: "ambassador"
      external_url: mmani.rc.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443
      rpcport: 15014
      quorumport: 15013
      portRaft: 15015
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
