apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: networkmapma
  annotations:
    fluxcd.io/automated: "false"
  namespace: smani-ns
spec:
  releaseName: networkmapma
  interval: 1m
  chart:
    spec:
      chart: platforms/r3-corda/charts/nms-tls
      sourceRef:
        kind: GitRepository
        name: flux-dev-mani
        namespace: flux-dev-mani
  values:
    nodeName: networkmapma
    metadata:
      namespace: smani-ns
    image:
      authusername: sa
      containerName: ghcr.io/hyperledger/bevel-networkmap-linuxkit:latest
      env:
      - name: NETWORKMAP_PORT
        value: 8080
      - name: NETWORKMAP_ROOT_CA_NAME
        value: CN=Network Map,OU=FRA,O=FRA,L=Berlin,C=DE
      - name: NETWORKMAP_TLS
        value: true
      - name: NETWORKMAP_DB
        value: /opt/networkmap/db
      - name: DB_USERNAME
        value: networkmapma
      - name: NETWORKMAP_AUTH_USERNAME
        value: sa
      - name: DB_URL
        value: mongodb-networkmapma
      - name: DB_PORT
        value: 27017
      - name: DATABASE
        value: admin
      - name: NETWORKMAP_CACHE_TIMEOUT
        value: 60S
      - name: NETWORKMAP_MONGOD_DATABASE
        value: networkmap
      imagePullSecret: regcred
      tlsCertificate: true
      initContainerName: ghcr.io/hyperledger/alpine-utils:1.0
      mountPath:
          basePath: /opt/networkmap
    storage:
      memory: 512Mi
      mountPath: "/opt/h2-data"
      name: awsstorageclass
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordanetworkmapma
      serviceaccountname: vault-auth
      secretprefix: networkmapma
      certsecretprefix: networkmapma/data/certs
      dbcredsecretprefix: networkmapma/data/credentials/mongodb
      secretnetworkmappass: networkmapma/data/credentials/userpassword
      tlscertsecretprefix: networkmapma/data/tlscerts
      dbcertsecretprefix: networkmapma/data/certs
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
      dburl: mongodb-networkmapma:27017
    service:
      port: 8080
      targetPort: 8080
      type: ClusterIP
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    ambassador:
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
