apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmanicmaniquorum
  namespace: cmani-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cmanicmaniquorum
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/node_quorum_member
    sourceRef:
      kind: GitRepository
      name: flux-dev-mani
      namespace: flux-dev-mani
  values:
    replicaCount: 1
    metadata:
      namespace: cmani-quo
      labels:
    helmVersion: v3
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: cmani
      status: default
      consensus: raft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
