apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmanicmanitessera
  namespace: cmani-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cmanicmanitessera
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/node_tessera
    sourceRef:
      kind: GitRepository
      name: flux-dev-mani
      namespace: flux-dev-mani
  values:
    replicaCount: 1
    metadata:
      namespace: cmani-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      pullPolicy: IfNotPresent
    node:
      name: cmani
      status: default
      consensus: raft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretengine: secretsv2
      tmsecretpath: cmani-quo/crypto/cmani/tm
      secretprefix: secretsv2/data/cmani-quo/crypto/cmani
      serviceaccountname: vault-auth
      keyname: quorum
      role: vault-role
      authpath: quorumcmani
    proxy:
      provider: "ambassador"
      external_url: cmani.rc.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443
      rpcport: 15011
      quorumport: 15010
      clientport: 8888
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
