---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmanicmaniquorum
  namespace: cmani-quo
  annotations:
    fluxcd.io/automated: 'false'
spec:
  releaseName: cmanicmaniquorum
  interval: 1m
  chart:
    spec:
      chart: platforms/quorum/charts/node_quorum_member
      sourceRef:
        kind: GitRepository
        name: flux-dev-mani
        namespace: flux-dev-mani
  values:
    replicaCount: 1
    images:
      node: 'quorumengineering/quorum:21.4.2'
      alpineutils: 'index.docker.io/hyperledgerlabs/alpine-utils:1.0'
      tessera: 'quorumengineering/tessera:21.7.3'
      busybox: busybox
      mysql: 'mysql/mysql-server:5.7'
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi