##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build corda os docker images triggered by :
#  - push on develop branch for latest tags
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Corda Opensource docker images

on:
  workflow_dispatch:
    inputs:
      corda_version:
        description: 'Enter Corda OS Version to build'
        required: true
        default: '4.7'
        type: choice
        options:
        - '4.4'
        - '4.7'
      gmaps_key:
        description: 'Enter Google Maps API key'
        required: false
        default: 'Google API key for Network Map'
  create:
    tags:
      - v*
  push:
    branches:
      - cor-bug
    paths:
      - '.github/workflows/corda_images_publish.yaml'
      - 'examples/supplychain-app/corda/cordApps_springBoot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to develop branch, create docker tags latest

  publish:
    # if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Publish to Github Packages
      run: |
        WDIR=`pwd`

        cd ${WDIR}/examples/supplychain-app/corda/cordApps_springBoot
        ./gradlew clean
        ./gradlew build
        ./gradlew publish --stacktrace
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_USER_NAME: ${{ github.actor }}